### ISSUE TITLE
Dates aren't parsed correctly in Safari

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/text-metadata-parser#11]
On the example you have a date listed as year-month-day, e.g. `YYYY-MM-DD`, but that doesn't work in Safari.

**Comment by saibotsivad** [comment]
Also possibly IE. See this related discussion over at the momentjs repo: https://github.com/moment/moment/issues/1407

**Comment by TehShrike** [comment]
On this repo, it's only a documentation issue.  An issue about date validation should be made in weak-type-wizard.

**Comment by TehShrike** [comment]
hmm, how does this issue relate to https://github.com/TehShrike/weak-type-wizard/issues/2 ?

I think a better description of "doesn't work" is required if any date validation was going to be added to text-metadata-parser.
